server:
  port: 7070

spring:
  application:
    name: ms-config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/markmercado1/microservicios.git # repositorio
          searchPaths:
            - config-data-postgres
            - config-data-mysql
          default-label: main

  security:
    user:
      name: root
      password: 123456
